hashicorp/terraform-provider-scaffolding-framework

- .github/workflows/test.yml
Encouraging new providers to also test against the newest Terraform CLI minor version. Over time as Terraform CLI's 1.0 compatibility is further solidified/proven, it is unclear whether testing each minor version should be necessary or encouraged.
> .github/workflows: Add Terraform CLI 1.1 testing

- .github/workflows/test.yml
Reference: #24 
The `go test` command cannot detect any issues when running `go generate`. This ensures that any `go generate` commands can successfully execute, while also ensuring there are no dangling Git differences afterwards to prevent cases where the documentation is not symmetrically updated.
> .github/workflows: Add `go generate` testing to CI

- internal/provider/example_data_source.go
- internal/provider/example_resource.go
- internal/provider/provider.go
This is a quick method for compilation errors to be raised should the types not satisfy the expected framework interfaces.
> internal/provider: Add compilation based interface assertions

- .github/workflows/release.yml
- .github/workflows/test.yml
This PR contains the following:
- Enable caching of Go dependencies by default - see [here][0]
- Detect Go version using `go.mod` – see [here][1]
[0]: https://github.com/actions/setup-go#caching-dependency-files-and-build-outputs
[1]: https://github.com/actions/setup-go#getting-go-version-from-the-gomod-file
> Cache Go dependencies and detect Go version in GitHub Action workflows

- .github/workflows/release.yml
The main blocker and reason for the fork (support of subkeys) seems to be resolved now:
https://github.com/crazy-max/ghaction-import-gpg/issues/58
--- 
Unrelated: I noticed [this action](https://github.com/hashicorp/terraform-provider-scaffolding-framework/blob/main/.github/workflows/add-content-to-project.yml) also, which doesn't seem relevant for this repo - was that perhaps accidentally copied from somewhere else?
> ci: replace forked GH action with latest upstream

- docs/index.md
- go.mod
- go.sum
- internal/provider/example_data_source.go
- internal/provider/example_resource.go
- internal/provider/provider.go
_Merge is pending framework tagged release with these changes. The framework will support the existing DataSourceType and ResourceType until the following release to allow provider developers to migrate._
Reference: https://github.com/hashicorp/terraform-plugin-framework/pull/472
> Updates for framework `provider.DataSourceType` and `provider.ResourceType` deprecations

- .github/workflows/release.yml
- .github/workflows/test.yml
Reference: https://github.com/hashicorp/terraform-providers-devex-internal/issues/118
> .github/workflows: Pin actions versions to SHAs

- go.mod
- go.sum
- internal/provider/example_data_source_test.go
- internal/provider/example_resource_test.go
Reference: https://discuss.hashicorp.com/t/announcing-the-terraform-plugin-testing-module/49914
This will ensure that developers cloning this template repository will get the most current Go module for provider testing.
> Migrate to terraform-plugin-testing

- docs/resources/scaffolding_example.md
- internal/provider/example_resource.go
- internal/provider/example_resource_test.go
Reference: https://developer.hashicorp.com/terraform/plugin/framework/resources/default
New example attribute highlights terraform-plugin-framework v1.2.0+ `Default` functionality for resource attributes. While the scaffolding code is not meant to be exhaustive of all available framework functionality, this new built-in feature is important enough to highlight.
> resource/example: Add defaulted attribute

- README.md
rewrites learn.hashicorp.com and terraform.io/docs/* links in readme.md to link to developer.hashicorp.com
> update readme with links to hashicorp developer

- .goreleaser.yml
Following rebranding, the term "Terraform Cloud" has been replaced with "HCP Terraform" throughout.
> Replacing "Terraform Cloud" with "HCP Terraform"

- go.mod
- internal/provider/example_function_test.go
Reference: https://github.com/hashicorp/terraform-provider-scaffolding-framework/pull/220
Consuming developers should not directly need to worry about `github.com/hashicorp/go-version` unless they want to use that Go module. Provider-defined functions testing was releasing in this template repository before the Terraform 1.8.0 version variable in the terraform-plugin-testing `tfversion` package was available. Now that the variable is present, we can remove go-version as a direct dependency, simplifying both the code and dependency management slightly.
> Use tfversion variables instead of go-version directly for function testing

- .github/workflows/release.yml
- .goreleaser.yml
Reference: https://goreleaser.com/deprecations/#removed-in-v2
Closes #227
> Update GoReleaser configuration for version 2

- .golangci.yml
* vet is deprecated and has been replaced by govet.
```console
$ golangci-lint run
WARN [lintersdb] The name "vet" is deprecated. The linter has been renamed to: govet.
```
> chore: change to `govet`

- README.md
- go.mod
Ref: https://github.com/hashicorp/terraform-providers-devex-internal/issues/182
Bumps the minimum Go module to 1.22.7
> all: Bump minimum Go module version to 1.22

- .github/workflows/test.yml
- README.md
Latest GHA images don't have terraform installed by default, ref: https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md
This PR also switches the build step to the recently adjusted tools folder targeted by `make generate`
> workflows: Add setup-terraform before doc generation step

- .golangci.yml
Since Go1.22 (loopvar) this linter is no longer relevant. Replaced by copyloopvar. 
See https://golangci-lint.run/usage/linters/#exportloopref
> chore: replace with `copyloopvar`

- .github/dependabot.yml
Now that we have a separate `tools` directory, we should ensure the Go module dependencies are kept up-to-date there as well 👍🏻
> Update dependabot config to include tools directory

- internal/provider/example_data_source_test.go
- internal/provider/example_ephemeral_resource_test.go
- internal/provider/example_function_test.go
- internal/provider/example_resource_test.go
As [mentioned](https://developer.hashicorp.com/terraform/plugin/testing/acceptance-tests/teststep#legacy-check-function) in the acceptance tests documentation, [Check](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-testing/helper/resource#TestStep:~:text=on%20this%20step.-,Check,-TestCheckFunc%0A%0A%09//%20Destroy%20will) is now legacy and has been replaced by the new [plan](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-testing@v1.11.0/plancheck) and [state](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-testing@v1.11.0/statecheck) check APIs.
This change migrates from the legacy plugin testing API to the new plan and state check API, which brings improved testing capabilities.
This makes it easier for provider developers to adopt these new APIs.
I’ve …
> provider: migrate to the new plan and state check API

- .golangci.yml
- Replace `max-per-linter` with `max-issues-per-linters`
- Replace `tenv` linter with `usetesting`
> Chore: golangci-lint fixes
